#!/usr/bin/env bash
# Installs ZeroTier, Python venv, proxy files, and systemd unit.
# Does NOT start the proxy until activate.sh is run with assigned ports.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${PROXYPI_INSTALL_DIR:-${HOME}/proxy}"
SERVICE_NAME="${PROXYPI_SERVICE_NAME:-improved_proxy.service}"
CONFIG_FILE="${INSTALL_DIR}/config.defaults"
NODE_INFO="${INSTALL_DIR}/node-info.env"

log() { echo "[*] $*"; }
warn() { echo "[!] $*" >&2; }
die() { echo "[-] $*" >&2; exit 1; }

require_linux() {
  [[ "$(uname -s)" == "Linux" ]] || die "This installer only supports Linux (Raspberry Pi OS / Debian)."
}

detect_user() {
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    echo "${SUDO_USER}"
  else
    id -un
  fi
}

download_file() {
  local dest="$1"
  local url="$2"
  curl -fsSL "$url" -o "$dest"
}

load_config() {
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    download_file "${CONFIG_FILE}" "${REPO_RAW}/install/config.defaults"
  fi
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"
  [[ -n "${ZEROTIER_NETWORK_ID:-}" && "${ZEROTIER_NETWORK_ID}" != "REPLACE_ME" ]] \
    || die "ZEROTIER_NETWORK_ID is not configured in ${CONFIG_FILE}. Ask the network operator."
}

install_apt_packages() {
  if ! command -v apt-get >/dev/null 2>&1; then
    warn "apt-get not found; ensure python3, python3-venv, curl, and git are installed."
    return
  fi
  log "Installing system packages"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    python3 python3-venv python3-pip curl ca-certificates
}

install_zerotier() {
  if command -v zerotier-cli >/dev/null 2>&1; then
    log "ZeroTier already installed"
    return
  fi
  log "Installing ZeroTier"
  curl -fsSL https://install.zerotier.com | sudo bash
  sudo systemctl enable --now zerotier-one
}

join_zerotier() {
  local network_id="$1"
  log "Joining ZeroTier network ${network_id}"
  sudo zerotier-cli join "${network_id}" || true
  sleep 2
}

download_proxy_files() {
  log "Downloading proxy files to ${INSTALL_DIR}"
  mkdir -p "${INSTALL_DIR}"
  download_file "${INSTALL_DIR}/proxyscript.py" "${REPO_RAW}/proxyscript.py"
  download_file "${INSTALL_DIR}/requirements.txt" "${REPO_RAW}/requirements.txt"
  cp -f "${SCRIPT_DIR}/config.defaults" "${CONFIG_FILE}" 2>/dev/null || true
}

setup_venv() {
  log "Creating Python virtual environment"
  python3 -m venv "${INSTALL_DIR}/venv"
  "${INSTALL_DIR}/venv/bin/pip" install --upgrade pip -q
  "${INSTALL_DIR}/venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt" -q
}

setup_log_dir() {
  local log_dir="${PROXY_LOG_DIR:-/var/log/proxy}"
  log "Preparing log directory ${log_dir}"
  sudo mkdir -p "${log_dir}"
  sudo chown "$(detect_user):$(id -gn "$(detect_user)")" "${log_dir}"
  sudo chmod 755 "${log_dir}"
}

install_systemd_service() {
  local run_user
  local home_dir
  run_user="$(detect_user)"
  home_dir="$(eval echo "~${run_user}")"
  local unit_path="/etc/systemd/system/${SERVICE_NAME}"

  log "Installing systemd service ${SERVICE_NAME}"
  sudo tee "${unit_path}" >/dev/null <<EOF
[Unit]
Description=Improved Proxy Service
After=network-online.target zerotier-one.service
Wants=network-online.target

[Service]
Type=simple
User=${run_user}
Group=${run_user}
WorkingDirectory=${home_dir}/proxy
EnvironmentFile=-${home_dir}/proxy/proxy.env
ExecStart=${home_dir}/proxy/venv/bin/python3 ${home_dir}/proxy/proxyscript.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
}

write_node_info() {
  local zt_address zt_node_id zt_ip hostname
  zt_address="$(sudo zerotier-cli info 2>/dev/null | awk '/address/ {print $3}')"
  zt_node_id="${zt_address}"
  hostname="$(hostname)"
  zt_ip="$(ip -4 addr show 2>/dev/null | awk '/inet 10\.147\./ {print $2}' | cut -d/ -f1 | head -1)"

  cat >"${NODE_INFO}" <<EOF
# Generated by proxypi setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOSTNAME=${hostname}
ZT_NODE_ID=${zt_node_id}
ZT_IP=${zt_ip:-pending}
INSTALL_DIR=${INSTALL_DIR}
SERVICE_NAME=${SERVICE_NAME}
STATUS=awaiting_activation
EOF
  chmod 600 "${NODE_INFO}"
}

print_next_steps() {
  local zt_node_id hostname
  # shellcheck disable=SC1090
  source "${NODE_INFO}"
  hostname="${HOSTNAME}"
  zt_node_id="${ZT_NODE_ID}"

  cat <<EOF

================================================================================
 Proxy Pi setup complete — awaiting network approval
================================================================================

Hostname:        ${hostname}
ZeroTier Node:   ${zt_node_id}
Install dir:     ${INSTALL_DIR}
Service:         ${SERVICE_NAME} (installed, not started)

NEXT STEPS
----------
1. Send the operator your ZeroTier Node ID:
      ${zt_node_id}

2. Wait for ZeroTier approval on the network.

3. After approval, the operator will send you SOCKS/HTTP ports and a
   one-time activation command. It will look like:

      curl -fsSL ${REPO_RAW}/install/activate.sh | \\
        SOCKS_PORT=18100 HTTP_PORT=58100 RADIUS_SECRET='***' bash

4. Check status:
      systemctl status ${SERVICE_NAME}
      tail -f ${PROXY_LOG_DIR:-/var/log/proxy}/proxy.log

Node info saved to: ${NODE_INFO}
================================================================================
EOF
}

main() {
  require_linux
  mkdir -p "${INSTALL_DIR}"

  if [[ -f "${CONFIG_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${CONFIG_FILE}"
  else
    REPO_RAW="${PROXYPI_REPO_URL:-https://raw.githubusercontent.com/conthegreat/proxypi-script/main}"
    download_file "${CONFIG_FILE}" "${REPO_RAW}/install/config.defaults"
    # shellcheck disable=SC1090
    source "${CONFIG_FILE}"
  fi

  load_config
  install_apt_packages
  install_zerotier
  join_zerotier "${ZEROTIER_NETWORK_ID}"
  download_proxy_files
  setup_venv
  setup_log_dir
  install_systemd_service
  write_node_info
  print_next_steps
}

main "$@"