#!/usr/bin/env bash
# Installs ZeroTier, Python venv, proxy files, and systemd unit.
# Does NOT start the proxy until activate.sh is run with assigned ports.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${PROXYPI_INSTALL_DIR:-${HOME}/proxy}"
SERVICE_NAME="${PROXYPI_SERVICE_NAME:-improved_proxy.service}"
CONFIG_FILE="${INSTALL_DIR}/config.defaults"
NODE_INFO="${INSTALL_DIR}/node-info.env"

log() { echo "[*] $*"; }
warn() { echo "[!] $*" >&2; }
die() { echo "[-] $*" >&2; exit 1; }

require_linux() {
  [[ "$(uname -s)" == "Linux" ]] || die "This installer only supports Linux (Raspberry Pi OS / Debian)."
}

detect_user() {
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    echo "${SUDO_USER}"
  else
    id -un
  fi
}

download_file() {
  local dest="$1"
  local url="$2"
  curl -fsSL "$url" -o "$dest"
}

load_config() {
  if [[ ! -f "${CONFIG_FILE}" ]]; then
    download_file "${CONFIG_FILE}" "${REPO_RAW}/install/config.defaults"
  fi
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"
  [[ -n "${ZEROTIER_NETWORK_ID:-}" ]] \
    || die "ZEROTIER_NETWORK_ID is not configured in ${CONFIG_FILE}. Ask the network operator."
}

install_apt_packages() {
  if ! command -v apt-get >/dev/null 2>&1; then
    warn "apt-get not found; ensure python3, python3-venv, curl, and git are installed."
    return
  fi
  log "Installing system packages"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    python3 python3-venv python3-pip curl ca-certificates iproute2
}

install_zerotier() {
  if command -v zerotier-cli >/dev/null 2>&1; then
    log "ZeroTier already installed"
    return
  fi
  log "Installing ZeroTier"
  curl -fsSL https://install.zerotier.com | sudo bash
  sudo systemctl enable --now zerotier-one
}

join_zerotier() {
  local network_id="$1"
  log "Joining ZeroTier network ${network_id}"
  sudo zerotier-cli join "${network_id}" || true
  sleep 2
}

download_proxy_files() {
  log "Downloading proxy files to ${INSTALL_DIR}"
  mkdir -p "${INSTALL_DIR}"
  download_file "${INSTALL_DIR}/proxyscript.py" "${REPO_RAW}/proxyscript.py"
  download_file "${INSTALL_DIR}/requirements.txt" "${REPO_RAW}/requirements.txt"
  cp -f "${SCRIPT_DIR}/config.defaults" "${CONFIG_FILE}" 2>/dev/null || true
}

setup_venv() {
  log "Creating Python virtual environment"
  python3 -m venv "${INSTALL_DIR}/venv"
  "${INSTALL_DIR}/venv/bin/pip" install --upgrade pip -q
  "${INSTALL_DIR}/venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt" -q
}

setup_log_dir() {
  local log_dir="${PROXY_LOG_DIR:-/var/log/proxy}"
  log "Preparing log directory ${log_dir}"
  sudo mkdir -p "${log_dir}"
  sudo chown "$(detect_user):$(id -gn "$(detect_user)")" "${log_dir}"
  sudo chmod 755 "${log_dir}"
}

install_systemd_service() {
  local run_user
  local home_dir
  run_user="$(detect_user)"
  home_dir="$(eval echo "~${run_user}")"
  local unit_path="/etc/systemd/system/${SERVICE_NAME}"

  log "Installing systemd service ${SERVICE_NAME}"
  sudo tee "${unit_path}" >/dev/null <<EOF
[Unit]
Description=Improved Proxy Service
After=network-online.target zerotier-one.service
Wants=network-online.target

[Service]
Type=simple
User=${run_user}
Group=${run_user}
WorkingDirectory=${home_dir}/proxy
EnvironmentFile=${home_dir}/proxy/proxy.env
Environment=PYTHONUNBUFFERED=1
ExecStart=${home_dir}/proxy/venv/bin/python3 ${home_dir}/proxy/proxyscript.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
}

get_zerotier_node_id() {
  # zerotier-cli info format: "200 info <10-char-address> <version> <ONLINE|OFFLINE>"
  # Prefer JSON when available; never require the word "address" (not present in text form).
  local node_id=""
  if sudo zerotier-cli info -j >/dev/null 2>&1; then
    node_id="$(
      sudo zerotier-cli info -j 2>/dev/null \
        | python3 -c 'import json,sys; print(json.load(sys.stdin).get("address",""))' 2>/dev/null \
        || true
    )"
  fi
  if [[ -z "${node_id}" ]]; then
    node_id="$(sudo zerotier-cli info 2>/dev/null | awk '{print $3}' | head -1)"
  fi
  # Normalise to lowercase hex, strip junk
  node_id="$(echo "${node_id}" | tr 'A-F' 'a-f' | tr -cd 'a-f0-9')"
  echo "${node_id}"
}

write_node_info() {
  local zt_node_id zt_ip hostname
  zt_node_id="$(get_zerotier_node_id)"
  hostname="$(hostname)"
  zt_ip="$(ip -4 addr show 2>/dev/null | awk '/inet 10\.147\./ {print $2}' | cut -d/ -f1 | head -1)"

  if [[ -z "${zt_node_id}" || ${#zt_node_id} -lt 10 ]]; then
    warn "Could not read ZeroTier node ID automatically. Run: sudo zerotier-cli info"
  fi

  cat >"${NODE_INFO}" <<EOF
# Generated by proxypi setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOSTNAME=${hostname}
ZT_NODE_ID=${zt_node_id}
ZEROTIER_NODE_ID=${zt_node_id}
ZT_IP=${zt_ip:-pending}
INSTALL_DIR=${INSTALL_DIR}
SERVICE_NAME=${SERVICE_NAME}
STATUS=awaiting_activation
EOF
  chmod 600 "${NODE_INFO}"
}

print_next_steps() {
  local zt_node_id hostname zt_ip
  # shellcheck disable=SC1090
  source "${NODE_INFO}"
  hostname="${HOSTNAME}"
  zt_node_id="${ZT_NODE_ID:-}"
  zt_ip="${ZT_IP:-pending}"

  local join_url="https://proxypi.co.uk/join"
  local id_ok=1
  if [[ -z "${zt_node_id}" || ${#zt_node_id} -lt 10 ]]; then
    id_ok=0
    zt_node_id="(not detected — see below)"
  fi

  cat <<EOF

================================================================================
  SUCCESS — your Pi software is installed
================================================================================

  Nothing is live yet. The proxy service is installed but NOT started.
  You still need to register this device on the website (about 2 minutes).

--------------------------------------------------------------------------------
  YOUR DETAILS (copy these carefully)
--------------------------------------------------------------------------------

  Pi hostname:          ${hostname}
  ZeroTier Node ID:     ${zt_node_id}
  Network status:       joined (waiting for ProxyPi to approve this device)
  Private IP (if any):  ${zt_ip}

EOF

  if [[ "${id_ok}" -eq 1 ]]; then
    cat <<EOF
  >>> THIS IS THE CODE YOU NEED ON THE WEBSITE <<<

      ${zt_node_id}

  Copy the line above (10 letters/numbers). You will paste it into the form.

EOF
  else
    cat <<EOF
  >>> COULD NOT AUTO-DETECT YOUR NODE ID — run this command: <<<

      sudo zerotier-cli info

  Example output:
      200 info 4b8ecdb32a 1.16.2 ONLINE
               ^^^^^^^^^^
               copy this 10-character code

EOF
  fi

  cat <<EOF
--------------------------------------------------------------------------------
  WHAT TO DO NEXT (in order)
--------------------------------------------------------------------------------

  STEP 1 — Open the join page on a phone or computer browser
      ${join_url}

  STEP 2 — Fill in the form
      • Hostname:        ${hostname}   (or the name ProxyPi gave you)
      • Your email:      the email you use with ProxyPi
      • ZeroTier Node ID: ${zt_node_id}
      • Complete the security checkbox / CAPTCHA
      • Submit

  STEP 3 — Wait for ProxyPi
      We approve your device on the private network (often same day).
      You will then receive a one-time activation command by email/chat.
      It looks like this (do NOT invent values — only run what we send):

      curl -fsSL …/install/activate.sh | \\
        ACTIVATION_TOKEN='…' ACTIVATION_API_URL='https://proxypi.co.uk' bash

  STEP 4 — On this Pi, paste and run that activation command
      After it succeeds you should see:  [+] Proxy is running

  STEP 5 — Optional checks
      systemctl status ${SERVICE_NAME}
      tail -f ${PROXY_LOG_DIR:-/var/log/proxy}/proxy.log

--------------------------------------------------------------------------------
  NEED THE NODE ID AGAIN LATER?
--------------------------------------------------------------------------------

      sudo zerotier-cli info
      cat ${NODE_INFO}

  Help / join page:  ${join_url}
  Support:           support@proxypi.co.uk

================================================================================
EOF
}

print_banner() {
  cat <<EOF

================================================================================
  ProxyPi node installer
================================================================================
  This sets up your Raspberry Pi to join the ProxyPi residential network.
  It installs private networking (ZeroTier) and the proxy software.
  It does NOT start serving traffic until ProxyPi sends you an activation
  command after you register at https://proxypi.co.uk/join
================================================================================

EOF
}

main() {
  require_linux
  mkdir -p "${INSTALL_DIR}"
  print_banner

  if [[ -f "${CONFIG_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${CONFIG_FILE}"
  else
    REPO_RAW="${PROXYPI_REPO_URL:-https://raw.githubusercontent.com/conthegreat/proxypi-script/main}"
    download_file "${CONFIG_FILE}" "${REPO_RAW}/install/config.defaults"
    # shellcheck disable=SC1090
    source "${CONFIG_FILE}"
  fi

  load_config
  install_apt_packages
  install_zerotier
  join_zerotier "${ZEROTIER_NETWORK_ID}"
  download_proxy_files
  setup_venv
  setup_log_dir
  install_systemd_service
  write_node_info
  print_next_steps
}

main "$@"